client/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

# import views
from client.controllers import *

# app_name = 'client'
urlpatterns = [
    # url(r'^index', login_required(views.HostListView.as_view()), name='host-list'),
    # url(r'^new', login_required(views.HostCreate.as_view()), name='host-new'),
    url(r'^host$', login_required(host.index), name='host'),
    url(r'^host/new', login_required(host.new), name='host_new'),
    url(r'^host/dialog_new', login_required(host.dialog_new), name='host_dialog_new'),
    url(r'^host/edit/(\d{1,8})$', login_required(host.edit), name='host_edit'),
    url(r'^host/delete/(\d{1,8})$', login_required(host.delete), name='host_delete'),
    url(r'^host/ajax_valid_ip$', login_required(host.ajax_valid_ip),
        name='host_ajax_valid_ip'),

    url(r'^host_group$', login_required(host_group.index), name='host_group_index'),
    url(r'^host_group/new', login_required(host_group.new), name='host_group_new'),
    url(r'^host_group/edit/(\d{1,8})$', login_required(host_group.edit), name='host_group_edit'),
    url(r'^host_group/delete/(\d{1,8})$', login_required(host_group.delete), name='host_group_delete'),

    url(r'^$', login_required(role_manage.index), name='role_manage_index'),
    url(r'^role_manage$', login_required(role_manage.index), name='role_manage_index'),
    url(r'^role_manage/new', login_required(role_manage.new), name='role_manage_new'),
    url(r'^role_manage/edit/(\d{1,8})$', login_required(role_manage.edit), name='role_manage_edit'),
    url(r'^role_manage/delete/(\d{1,8})$', login_required(role_manage.delete), name='role_manage_delete'),
    url(r'^role_manage/ajax_valid_name$', login_required(role_manage.ajax_valid_name),
        name='role_manage_ajax_valid_name'),

    url(r'^dynamic_var$', login_required(dynamic_var.index), name='dynamic_var_index'),
    url(r'^dynamic_var/new', login_required(dynamic_var.new), name='dynamic_var_new'),
    url(r'^dynamic_var/edit/(\d{1,8})$', login_required(dynamic_var.edit), name='dynamic_var_edit'),
    url(r'^dynamic_var/delete/(\d{1,8})$', login_required(dynamic_var.delete), name='dynamic_var_delete'),
    url(r'^dynamic_var/ajax_valid_name$', login_required(dynamic_var.ajax_valid_name),
        name='dynamic_var_ajax_valid_name'),

    url(r'^user_operate$', login_required(user_operate.index), name='user_operate_index'),
    url(r'^user_operate/get_result$', login_required(user_operate.get_result), name='user_operate_get_result'),

    url(r'^group_operate$', login_required(group_operate.index), name='group_operate_index'),
    url(r'^group_operate/get_result$', login_required(group_operate.get_result), name='group_operate_get_result'),

    url(r'^cmd_operate$', login_required(cmd_operate.index), name='cmd_operate_index'),
    url(r'^cmd_operate/get_result$', login_required(cmd_operate.get_result), name='cmd_operate_get_result'),

    url(r'^file_operate$', login_required(file_operate.index), name='file_operate_index'),
    url(r'^file_operate/get_result$', login_required(file_operate.get_result), name='file_operate_get_result'),

    url(r'^send_file$', login_required(send_file.index), name='send_file_index'),
    url(r'^send_file/get_result$', login_required(send_file.get_result), name='send_file_get_result'),
]

devops_tool/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.contrib import admin
from . import views

urlpatterns = [
    # url(r'^$', login_required(views.home), name='home'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/role_manage'}, name='logout'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^admin/', admin.site.urls),
    url(r'', include('client.urls')),
    url(r'', include('workflow.urls')),

]

client/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from common.ext_models import Base, CommonName, CommonDescribe
from django.utils.translation import ugettext_lazy as _



class DynamicVar(CommonDescribe, CommonName, Base):
    name = models.CharField("名称", max_length=20, unique= True)
    def __str__(self):
        return self.name

    def __unicode__(self):
        return unicode(self.name) or u''

class RoleManage(CommonDescribe, CommonName, Base):
    # name = models.CharField("名称", max_length=20, unique= True)
    # name===》Ansible hosts分组用到
    # playbook===》Ansible-playbook脚本用到
    # tag===》标示Ansible-playbook 参数分组

    # name = models.CharField("名称", max_length=20)
    num = models.IntegerField(verbose_name="顺序编号")
    timeout = models.IntegerField(verbose_name="超时时长(s)", default=180)
    playbook = models.CharField("Playbook", max_length=255, blank=True, null= True)
    playbook_name = models.CharField("Playbook名称", max_length=50, blank=True, null= True)
    # playbook子任务数
    # step_count = models.IntegerField(default=0)
    # dynamic_vars = models.CharField("动态变量", max_length=255, blank=True, null= True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return unicode(self.name) or u''

    def host_ips(self):
        host_roles = self.host_role_set.all()
        return [host_role.host.ip for host_role in host_roles]

    def host_count(self):
        return len(self.host_ips())

    # def playbook_name(self):
    #     return self.playbook.split('.')[0]

    # 角色关联的动态参数
    def dynamic_variable_ids(self):
        role_dynamic_variables = self.role_dynamic_variable_set.all()
        return [rdv.dynamic_var.id for rdv in role_dynamic_variables]

class HostGroup(CommonName, Base):
    describe = models.CharField("描述", max_length=255, blank=True, null= True)

class Host(Base):
    # ip_addr = IPAddressField()
    # host_roles = models.CharField("角色", max_length=100, default='default_role')
    # host_group = models.ForeignKey(HostGroup, verbose_name="隶属组")
    username = models.CharField("用户名", max_length=30)
    password = models.CharField(_('password'), max_length=30)
    # ssh_key = models.CharField("SSH key", max_length=255, blank=True, null= True)
    ip = models.GenericIPAddressField("IP")
    port = models.IntegerField("端口", default=22)
    conn_status = models.BooleanField("连接状态", default=False)
    describe = models.CharField("备注", max_length=255, blank=True, null= True)

    def __str__(self):
        return self.ip

    def status(self):
        STATUS = {0: "离线", 1: "在线"}
        return STATUS[int(self.conn_status)]

    def role_names(self):
        host_roles = self.host_role_set.all()
        role_name_list = [host_role.role_manage.name for host_role in host_roles]
        return ','.join(role_name_list)


class Host_Role(Base):
    host = models.ForeignKey(Host)
    role_manage = models.ForeignKey(RoleManage)

class Dynamic_Variable_Host(Base):
    dynamic_var = models.ForeignKey(DynamicVar)
    host = models.ForeignKey(Host)

class Role_Dynamic_Variable(Base):
    role_manage = models.ForeignKey(RoleManage)
    dynamic_var = models.ForeignKey(DynamicVar)

client/controllers/cmd_operate.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from client.controllers import *
from client.forms import SendCmdForm


def index(request):
    title_name = _title_name()
    class_name = _class_name()
    init_date = {}
    form = SendCmdForm(initial=init_date)
    object_list = ext_helper.get_objects(request, 'Host')
    render_url = "%s/%s" % (_class_name(), 'index.html')
    return render(request, render_url, locals())


def get_result(request):
    if request.method == 'POST':  # 当提交表单时
        form = SendCmdForm(request.POST)  # form 包含提交的数据
        if form.is_valid():  # 如果提交的数据合法
            date = request.POST
            tid = ext_helper.generate_tid()
            _ansible_api(tid, date)
            redis_result = redis_api.RedisResult(tid)
            object_list = redis_result.get_instance()
            pattern = "{tid}*".format(tid=tid)
            for key in redis_api.Rs.scan_iter(match=pattern):
                redis_api.Rs.delete(key)
    else:
        error_msg = "Status 400: 错误的请求方式!"
    render_url = "base/_result.html"
    return render(request, render_url, locals())


def _ansible_api(tid, form_date):
    hosts = form_date['hosts']
    ext_vars = {"ansible_ssh_user": "root", "ansible_ssh_pass": "root"}
    # params = {k: v for k, v in form_date.iteritems() if k not in ['hosts', 'csrfmiddlewaretoken']}
    params = form_date['cmd']
    ansible_api.api(tid, 'shell', hosts, params, ext_vars)


def _title_name():
    return '执行命令'


def _class_name():
    return 'cmd_operate'

client/controllers/dynamic_var.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from client.forms import DynamicVarForm
from client.models import DynamicVar
from client.controllers import *

def index(request):
    title_name = _title_name()
    class_name = _class_name()
    msg = ext_helper.get_msg(request)
    object_list = ext_helper.get_objects(request, 'DynamicVar')
    render_url = "%s/%s" % (_class_name(), 'index.html')
    return render_to_response(render_url, locals())


def new(request):
    title_name = _title_name()
    class_name = _class_name()
    operation = "添加"
    if request.method == 'POST':  # 当提交表单时
        instance, msg= ext_helper.create_date(request, 'DynamicVar', 'name')
    form = DynamicVarForm()
    return render(request, 'dynamic_var/form.html', locals())


def edit(request, id):
    id = ext_helper.to_int(id)
    title_name = _title_name()
    class_name = _class_name()
    operation = "编辑"
    if request.method == 'POST':  # 当提交表单时
        result_status, msg = ext_helper.update_date(request, id, 'DynamicVar', 'name')
        request.session['msg'] = msg
        if result_status:
            return index(request)
        else:
            return render(request, 'dynamic_var/form.html', locals())
    else:
        host = DynamicVar.objects.get(pk=id)
        form = DynamicVarForm(instance=host)
        return render(request, 'dynamic_var/form.html', locals())


def delete(request, id):
    id = ext_helper.to_int(id)
    obj = DynamicVar.objects.get(pk=id)
    obj.delete()
    if obj.id:
        request.session['msg'] = "数据删除失败!"
    else:
        request.session['msg'] = "数据删除成功!"
    return index(request)

# 校验名称唯一性
def ajax_valid_name(request):
    name = request.GET['name']
    try:
        role_manage = DynamicVar.objects.get(name=name)
        msg = "{name}已存在。".format(name=name)
    except:
        msg = ''
    return HttpResponse(json.dumps({'msg': msg}), content_type='application/json')


def _title_name():
    return '变量'


def _class_name():
    return 'dynamic_var'

client/controllers/file_operate.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from client.controllers import *
from client.forms import CreateFileForm


def index(request):
    title_name = _title_name()
    class_name = _class_name()
    init_date = {}
    form = CreateFileForm(initial=init_date)
    object_list = ext_helper.get_objects(request, 'Host')
    render_url = "%s/%s" % (_class_name(), 'index.html')
    return render(request, render_url, locals())


def get_result(request):
    if request.method == 'POST':  # 当提交表单时
        form = CreateFileForm(request.POST)  # form 包含提交的数据
        if form.is_valid():  # 如果提交的数据合法
            date = request.POST
            tid = ext_helper.generate_tid()
            _ansible_api(tid, date)
            redis_result = redis_api.RedisResult(tid)
            object_list = redis_result.get_instance()
            pattern = "{tid}*".format(tid=tid)
            for key in redis_api.Rs.scan_iter(match=pattern):
                redis_api.Rs.delete(key)
    else:
        error_msg = "Status 400: 错误的请求方式!"
    render_url = "base/_result.html"
    return render(request, render_url, locals())


def _ansible_api(tid, form_date):
    hosts = form_date['hosts']
    ext_vars = {"ansible_ssh_user": "root", "ansible_ssh_pass": "root"}
    params = {k: v for k, v in form_date.iteritems() if k not in ['hosts', 'csrfmiddlewaretoken']}
    ansible_api.api(tid, 'file', hosts, params, ext_vars)


def _title_name():
    return '文件操作'


def _class_name():
    return 'file_operate'

client/controllers/group_operate.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from client.controllers import *
from client.forms import CreateGroupForm


def index(request):
    title_name = _title_name()
    class_name = _class_name()
    init_date = {'state': 'present', 'system': 'no'}
    form = CreateGroupForm(initial=init_date)
    object_list = ext_helper.get_objects(request, 'Host')
    render_url = "%s/%s" % (_class_name(), 'index.html')
    # render_url = "base/index.html"
    return render(request, render_url, locals())


def get_result(request):
    if request.method == 'POST':  # 当提交表单时
        form = CreateGroupForm(request.POST)  # form 包含提交的数据
        if form.is_valid():  # 如果提交的数据合法
            date = request.POST
            tid = ext_helper.generate_tid()
            _ansible_api(tid, date)
            redis_result = redis_api.RedisResult(tid)
            object_list = redis_result.get_instance()
            pattern = "{tid}*".format(tid=tid)
            for key in redis_api.Rs.scan_iter(match=pattern):
                redis_api.Rs.delete(key)
    else:
        error_msg = "Status 400: 错误的请求方式!"
    render_url = "base/_result.html"
    return render(request, render_url, locals())



def _ansible_api(tid, form_date):
    hosts = form_date['hosts']
    ext_vars = {"ansible_ssh_user": "root", "ansible_ssh_pass": "root"}
    params = {k: v for k, v in form_date.iteritems() if k not in ['hosts', 'csrfmiddlewaretoken']}
    ansible_api.api(tid, 'group', hosts, params, ext_vars)


def _title_name():
    return '用户组操作'


def _class_name():
    return 'group_operate'

client/controllers/host.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from client.forms import HostForm
from client.models import Host, RoleManage, Host_Role
from client.controllers import *

def index(request):
    title_name = _title_name()
    class_name = _class_name()
    msg = ext_helper.get_msg(request)
    object_list = ext_helper.get_objects(request, class_name.title())
    render_url = "%s/%s" % (_class_name(), 'index.html')
    return render_to_response(render_url, locals())


def new(request):
    title_name = _title_name()
    class_name = _class_name()
    role_manages = RoleManage.objects.filter(user_id=request.user.id)
    operation = "添加"
    if request.method == 'POST':  # 当提交表单时
        instance, msg= ext_helper.create_date(request, 'Host', 'ip')
        role_ids = request.POST.getlist('role_ids')
        for role_id in role_ids:
            Host_Role.objects.create(host_id=instance.id, role_manage_id=role_id, user_id=request.user.id)
    form = HostForm(initial={'port': 22})
    return render(request, 'host/form.html', locals())


def dialog_new(request):
    dialog_title = "添加节点"
    if request.method == 'GET':
        role_manages = RoleManage.objects.filter(user_id=request.user.id)
        form_url = '/%s/%s' % (_class_name(), 'dialog_new')
        form = HostForm(initial={'host_group': 1, 'port': 22})
        return render(request, 'host/dialog_form.html', locals())
    else:
        host_role_list = request.POST.getlist('host_roles')
        d = {'host_roles': ','.join(host_role_list)}
        instance, msg = ext_helper.create_date(request, 'Host', 'ip', d)
        request.session['msg'] = msg
        return index(request)

def edit(request, id):
    id = ext_helper.to_int(id)
    title_name = _title_name()
    class_name = _class_name()
    operation = "编辑"
    role_manages = RoleManage.objects.filter(user_id=request.user.id)
    if request.method == 'POST':  # 当提交表单时
        result_status, msg = ext_helper.update_date(request, id, 'Host', 'ip')
        Host_Role.objects.filter(host_id=id).delete()
        role_ids = request.POST.getlist('role_ids')
        for role_id in role_ids:
            Host_Role.objects.create(host_id=id, role_manage_id=role_id, user_id=request.user.id)

        request.session['msg'] = msg
        if result_status:
            return index(request)
        else:
            return render(request, 'host/form.html', locals())
    else:
        host = Host.objects.get(pk=id)
        select_role_list = host.host_role_set.all().values_list('role_manage_id', flat=True)
        select_role =  '_'.join(map(str, list(select_role_list)))
        form = HostForm(instance=host)
        return render(request, 'host/form.html', locals())


def delete(request, id):
    id = ext_helper.to_int(id)
    obj = Host.objects.get(pk=id)
    obj.delete()
    if obj.id:
        request.session['msg'] = "数据删除失败!"
    else:
        request.session['msg'] = "数据删除成功!"
    return index(request)


def ajax_valid_ip(request):
    ip = request.GET['ip']
    try:
        Host.objects.get(ip=ip)
        msg = "{ip}已存在。".format(ip=ip)
    except:
        msg = ''
    return HttpResponse(json.dumps({'msg': msg}), content_type='application/json')


def _title_name():
    return '节点'


def _class_name():
    return 'host'

client/templates/role_manage/_form.html
<form action="" method="post">{% csrf_token %}
    {% include 'includes/form_field.html' %}
    <div class="form-group">
        <label for="id_dynamic_vars">动态变量:</label>
        <table style="width: 100%;">
            <tr>
                {% for var in dynamic_vars %}
                    <td>
                        <label title="{{ var.name }}" for="id_dynamic_var_{{ forloop.counter }}">
                            <input id="id_dynamic_var_{{ forloop.counter }}" name="dynamic_vars" type="checkbox"
                                   value="{{ var.id }}">
                            {{ var.name|truncatechars:40 }}
                        </label>&nbsp;&nbsp;
                    </td>
                    {% ifnotequal forloop.counter|divisibleby:'4'  0 %}
                        </tr>
                        <tr>
                    {% endifnotequal %}
                {% endfor %}
        </table>
    </div>
    <div class="form-group">
        <span class="red">*</span>
        <label for="id_playbook">部署脚本:</label>
        &nbsp; <label for="playbook" class="error"></label>
        <table style="width: 100%;">
            <tr>
                {% for app in playbook_list %}
                    <td>
                        <label title="{{ app }}" for="id_playbook_{{ forloop.counter }}"> &nbsp;&nbsp;
                            <input id="id_playbook_{{ forloop.counter }}" name="playbook" type="radio"
                                   value="{{ app }}" {% ifequal role_manage.playbook app %}checked{% endifequal %}
                                   required>
                            {{ app|truncatechars:40 }}
                        </label>
                    </td>
                    {% ifnotequal forloop.counter|divisibleby:'3'  0 %}
                        </tr>
                        <tr>
                    {% endifnotequal %}
                {% endfor %}
        </table>
    </div>
    <input class="btn btn-default" id="submit" name="commit" type="submit" value="保存">
    <a href="/{{ class_name }}" class="btn btn-default">返回</a>
</form>

client/templates/role_manage/_js.html
<script>
    $(function () {
        // 初始化文本框的宽度为50%
        $('.form-control[id^=id_]').each(function(){
            $(this).css('width', '50%');
        })

        // 编辑时候,勾选对应复选框
        var select_role = "{{role_manage.dynamic_variable_ids}}";
        $('[id^=id_dynamic_var_]').each(function () {
            val = $(this).val()
            if (select_role.indexOf(val) >= 0) {
                $(this).attr('checked', 'checked')
            }
        });
        // 名称校验
        $('#id_name').addClass('valid_letter_num');
        check_uniq('name', '/role_manage/ajax_valid_name', 'submit')

        // 序号
        $('#id_num').attr('min', 1);
        $('#id_num').attr('max', 50);

        // 超时时间
        $('#id_timeout').attr('min', 0);
        $('#id_timeout').attr('max', 10800);

        // 应用
        $('[name=playbook]').each(function () {
            $(this).rules('remove', 'required')
        })

    })
    $("form").validate();
</script>

client/templates/role_manage/dialog_form.html
{% extends 'extends/dialog_body.html' %}
{% block body %}
    <div style="width: 90%; margin-left: 5%">
        {% include "./_form.html" %}
    </div>
{% endblock %}
{% block custom_js %}
    {% include './_js.html' %}
{% endblock %}

client/templates/role_manage/form.html
{% extends "extends/table.html" %}
{% load ext_template %}
{% block title %}{{ title_name }}{% endblock %}
{% block page-header %}{{ operation }}{{ title_name }}{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            {% include "./_form.html" %}
        </div>
    </div>
{% endblock %}
{% block custom_js %}
    {% include './_js.html' %}
{% endblock %}

client/templates/role_manage/index.html
{% extends "extends/table.html" %}
{% block title %}{{ title_name }}{% endblock %}
{% block page-header %}{{ title_name }}{% endblock %}
{% block content %}
    <div class="dataTable_wrapper">
        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
            <tr>
                <th>序号</th>
                <th>角色名称</th>
                <th>部署脚本</th>
                <th>超时时长</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>

            {% for obj in object_list %}
                <tr class="{% cycle 'odd' 'even' %} gradeX">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.playbook }}</td>
                    <td>{{ obj.timeout }}</td>
                    <td class="center">
                        <a href="/{{ class_name }}/edit/{{ obj.id }}" class="btn btn-default">编辑</a>
                        <a href="/{{ class_name }}/delete/{{ obj.id }}" data-del="true" class="btn btn-default">删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <br/>
    <a href="/{{ class_name }}/new" class="btn btn-default">添加</a>
{% endblock %}
{% block custom_js %}
    <!--{#% include './_js.html' %}-->
{% endblock %}